### ISSUE TITLE
Finish struct ImageStorage using boost

### ISSUE THREAD

**Issue by michaelarakel** [MaryBagratunyan/GuessTheMovie#4]
It seems that there is no clear way of creating folders in pure c++ (there is a Windows API for that as well as a POSIX-based one).

I'd suggest using the boost library, particularly `boost::filesystem` namespace:

http://www.boost.org/doc/libs/1_54_0/libs/filesystem/doc/reference.html#exists

Particularly, pay attention to the functions:
`create_directories` and `exists`

**Comment by michaelarakel** [comment]
What do you think?

Actually I am a bit reluctant to make this change. We could use windows specific functions to achieve this (since all of you are working from windows)

**Comment by michaelarakel** [comment]
Who is going to take this?

**Comment by MaryBagratunyan** [comment]
so as no one reacted, I guess I should take that part

**Comment by MaryBagratunyan** [comment]
but also I've got some changes in structs that I'd like to show

**Comment by michaelarakel** [comment]
Since @Sakurada has already made a PR with usage of boost, I will assign this issue to her
